# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def karhooPods
  pod 'KarhooUISDK', :git => 'git@github.com:karhoo/karhoo-ios-ui-sdk.git', :tag => '1.6.1'
  #pod 'KarhooSDK', :git => 'git@github.com:karhoo/karhoo-ios-sdk.git', :tag => '1.5.1-rc1'
  pod 'KarhooSDK', '1.5.1'
end

def uikitComponentsPods
  use_frameworks!
  karhooPods
  # sample loading spinner until we make our trip allocation spinner in KarhooBookingViewController public
  pod 'SwiftSpinner'
end

target 'UIKit Karhoo Component' do

  uikitComponentsPods

  # Comment the next line if you don't want to use dynamic frameworks

  target 'UIKit Karhoo ComponentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIKit Karhoo ComponentUITests' do
    # Pods for testing
  end

end

target 'UIKit Karhoo Component Theme 1' do
  uikitComponentsPods
end

target 'UIKit Karhoo Component Theme 2' do
  uikitComponentsPods
end

target 'UIKit Karhoo Component Theme 3' do
  uikitComponentsPods
end

target 'SwiftUIComponents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  karhooPods
end

