# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
 

# Standard cocoapods specs source
source 'https://github.com/CocoaPods/Specs.git'

def sdkPods
  pod 'BraintreeDropIn'
  pod 'Braintree/PaymentFlow'
  pod 'KarhooSDK', '1.7.0'

end

target 'Network SDK SwiftUI Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Network SDK SwiftUI Sample
  sdkPods
end
