# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ui-sdk-dropin-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ui-sdk-dropin-sample
  pod 'KarhooSDK', '1.5.2'
  pod 'KarhooUISDK', :git => 'https://github.com/karhoo/karhoo-ios-ui-sdk.git', :tag => '1.6.2'

end
