# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def karhooPods
  pod 'KarhooUISDK', :git => 'https://github.com/karhoo/karhoo-ios-ui-sdk.git', :branch => 'develop'
  pod 'KarhooSDK', :git => 'https://github.com/karhoo/karhoo-ios-sdk.git', :branch => 'develop'
end

target 'UIKit Karhoo Component' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  karhooPods

  # sample loading spinner until we make our trip allocation spinner in KarhooBookingViewController public
  pod 'SwiftSpinner'

  target 'UIKit Karhoo ComponentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIKit Karhoo ComponentUITests' do
    # Pods for testing
  end

end

target 'SwiftUIComponents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  karhooPods
end

