# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIKit Karhoo Component' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIKit Karhoo Component
  pod 'SwiftSpinner'
  pod 'KarhooUISDK', :git => 'https://github.com/karhoo/karhoo-ios-ui-sdk.git', :branch => 'develop'
  pod 'KarhooSDK', :git => 'https://github.com/karhoo/karhoo-ios-sdk.git', :branch => 'develop'
  target 'UIKit Karhoo ComponentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIKit Karhoo ComponentUITests' do
    # Pods for testing
  end

end

target 'UISDK components sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UISDK components sample

  target 'UISDK components sampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UISDK components sampleUITests' do
    # Pods for testing
  end

end
